server:
  port: 8094
  tomcat:
    max-http-form-post-size: 1000MB

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/archive?characterEncoding=UTF-8&amp;serverTimezone=Asia/Seoul
    username: archiveuser
    password: archiveuser


  # jsp setting
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # live reload setting - auto reload
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 5MB
      max-request-size: 10MB
      location: C:\uploads\temp\bootS3


mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframwork.web : debug
    sql : off
    jdbc : off
    jdbc.sqlonly : debug


