spring:

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/archive?characterEncoding=UTF-8&amp;serverTimezone=Asia/Seoul
    username: root
    password: 12345


